create table if not exists public.waivers (
  id bigint generated by default as identity primary key,
  name text not null,
  agreed boolean not null default true,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists waivers_created_at_idx
  on public.waivers (created_at desc);

alter table public.waivers enable row level security;
